[[test]]
name = "length"
json = '''
{
    "array": [
        {
            "value": 1
        },
        {
            "value": 2
        }
    ]
}
'''

jfol = '''
Total: $$(array.length)
$array[number $$number/$$length: $value$$separator[
]]
'''

text = """
Total: 2
number 1/2: 1
number 2/2: 2`
"""