[[test]]
name = "simple"
json = '''
{
    "array": [
        {
            "package": {
                "name": "pack1"
            }
        },
        {
            "package": {
                "name": "pack2"
            }
        }
    ]
}
'''

jfol = '''
Packages Total: $$(array.length)\n$array[$$index: $(package.name)$$separator[\n]]
'''

text = """
Packages Total: 2\n0: pack1\n1: pack2
"""
